displayName: Correlation ID
type: middleware

import: github.com/navacloud/traefik-correlation-id-plugin

summary: 'This plugin adds a uuid7 correleation ID to the request headers'

testData:
  headerName: "X-Nava-Correlation-Id"
  legacyHeaderName: "X-Klz-Correlation-Id"
